/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simplebankingsystem;

/**
 *
 * @author Asus
 */
public class TransactionManagementWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransactionManagementWindow.class.getName());

   private int verifiedAccountId = -1; 
    private double currentAccountBalance = 0.0; 
    private String currentAccountOwner = "";
    
    // Connects to your existing DAO
    private TransactionDAO transactionDAO = new TransactionDAO();
    /**
     * Creates new form TransactionManagementWindow
     */
    public TransactionManagementWindow() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Withdraw = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAmout = new javax.swing.JTextField();
        Deposit = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Verification = new javax.swing.JButton();
        txtSearchBar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCurrentBalance = new javax.swing.JTextField();
        H = new javax.swing.JButton();
        B = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Withdraw.setBackground(java.awt.Color.red);
        Withdraw.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Withdraw.setText("Withdraw");
        Withdraw.addActionListener(this::WithdrawActionPerformed);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("Perform Transaction");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setText("Amount:");

        txtAmout.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtAmout, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAmout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Deposit.setBackground(java.awt.Color.green);
        Deposit.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Deposit.setText("Deposit");
        Deposit.addActionListener(this::DepositActionPerformed);

        Refresh.setBackground(java.awt.Color.cyan);
        Refresh.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Refresh.setText("Refresh Display");
        Refresh.addActionListener(this::RefreshActionPerformed);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Account Verification");

        Verification.setBackground(java.awt.Color.blue);
        Verification.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Verification.setText("Verify Account");
        Verification.addActionListener(this::VerificationActionPerformed);

        txtSearchBar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("Enter Account ID:");

        txtCurrentBalance.addActionListener(this::txtCurrentBalanceActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearchBar)
                                .addGap(18, 18, 18)
                                .addComponent(Verification, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCurrentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Verification)
                    .addComponent(txtSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(txtCurrentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        H.setBackground(java.awt.Color.pink);
        H.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        H.setText("History");
        H.addActionListener(this::HActionPerformed);

        B.setBackground(java.awt.Color.darkGray);
        B.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        B.setText("Back");
        B.addActionListener(this::BActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(H, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B)
                    .addComponent(Withdraw)
                    .addComponent(Refresh)
                    .addComponent(H))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawActionPerformed
        // TODO add your handling code here:
        // 1. Did they verify an account first?
    if (verifiedAccountId == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please verify an account first before withdrawing!", "Verification Required", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    String amountStr = txtAmout.getText().trim();
    
    if (amountStr.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter an amount to withdraw.", "Missing Amount", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    try {
        double amount = Double.parseDouble(amountStr);
        if (amount <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Withdrawal amount must be greater than zero.", "Invalid Amount", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 2. Process the Withdrawal
        // (Your TransactionDAO will automatically check if they have enough balance!)
        boolean success = transactionDAO.processTransaction(verifiedAccountId, amount, "Withdraw");
        
        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Withdrawal Successful!");
            
          // 3. Automatically update the current balance box on the screen!
            currentAccountBalance -= amount; // Subtract from the background variable
            txtCurrentBalance.setText("Owner: " + currentAccountOwner + "   |   Balance: ₱" + currentAccountBalance);
            
            txtAmout.setText("");
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid number for the amount.", "Invalid Input", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_WithdrawActionPerformed

    private void VerificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificationActionPerformed
        // TODO add your handling code here:
      String searchId = txtSearchBar.getText().trim();
    
        if (searchId.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter an Account ID to verify.", "Missing ID", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            int accId = Integer.parseInt(searchId);
            
            // Updated query to JOIN Customer and Account to get the owner's name
            String query = "SELECT a.balance, c.first_name, c.last_name FROM Account a JOIN Customer c ON a.customer_id = c.customer_id WHERE a.account_id = ?";
            
            try (java.sql.Connection conn = DBConnection.getConnection(); 
                 java.sql.PreparedStatement stmt = conn.prepareStatement(query)) {
                 
                 stmt.setInt(1, accId);
                 java.sql.ResultSet rs = stmt.executeQuery();
                 
                 if (rs.next()) {
                     // SUCCESS! Save details to background variables
                     verifiedAccountId = accId;
                     currentAccountBalance = rs.getDouble("balance");
                     currentAccountOwner = rs.getString("first_name") + " " + rs.getString("last_name");
                     
                     // Format the text field: Make text BIGGER and Centered
                     txtCurrentBalance.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 24));
                     txtCurrentBalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                     
                     // Display the formatted string
                     txtCurrentBalance.setText("Owner: " + currentAccountOwner + "   |   Balance: ₱" + currentAccountBalance);
                     
                     javax.swing.JOptionPane.showMessageDialog(this, "Account Verified Successfully!");
                 } else {
                     // FAILED! Reset everything
                     verifiedAccountId = -1;
                     currentAccountBalance = 0.0;
                     currentAccountOwner = "";
                     txtCurrentBalance.setText("");
                     javax.swing.JOptionPane.showMessageDialog(this, "Account not found!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                 }
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Account ID must be a valid number.", "Invalid Input", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_VerificationActionPerformed

    private void txtCurrentBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurrentBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurrentBalanceActionPerformed

    private void DepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositActionPerformed
        // TODO add your handling code here:
        // 1. Did they verify an account first?
    if (verifiedAccountId == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please verify an account first before depositing!", "Verification Required", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    String amountStr = txtAmout.getText().trim(); 
    
    if (amountStr.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter an amount to deposit.", "Missing Amount", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    try {
        double amount = Double.parseDouble(amountStr);
        if (amount <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Deposit amount must be greater than zero.", "Invalid Amount", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 2. Process the Deposit using your DAO
        boolean success = transactionDAO.processTransaction(verifiedAccountId, amount, "Deposit");
        
        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Deposit Successful!");
            
           // 3. Automatically update the current balance box on the screen!
            currentAccountBalance += amount; // Add to the background variable
            txtCurrentBalance.setText("Owner: " + currentAccountOwner + "   |   Balance: ₱" + currentAccountBalance);
            
            // Clear the amount box for the next transaction
            txtAmout.setText(""); 
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid number for the amount.", "Invalid Input", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_DepositActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        // Reset the tracker
    verifiedAccountId = -1;
    
    // Clear all text boxes
    txtSearchBar.setText("");
    txtCurrentBalance.setText("");
    txtAmout.setText("");
    currentAccountBalance = 0.0;
    currentAccountOwner = "";
    }//GEN-LAST:event_RefreshActionPerformed

    private void HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HActionPerformed
        // TODO add your handling code here:
          java.awt.EventQueue.invokeLater(() -> new TransactionHistoryWindow().setVisible(true));
           this.dispose();
    }//GEN-LAST:event_HActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(() -> new CustomerAccountWindow().setVisible(true));
          this.dispose();
    }//GEN-LAST:event_BActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TransactionManagementWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B;
    private javax.swing.JButton Deposit;
    private javax.swing.JButton H;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Verification;
    private javax.swing.JButton Withdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAmout;
    private javax.swing.JTextField txtCurrentBalance;
    private javax.swing.JTextField txtSearchBar;
    // End of variables declaration//GEN-END:variables
}
